### ISSUE TITLE
undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'

### ISSUE THREAD

**Issue by colinliuzelin** [yangao07/TideHunter#1]
When I compiled the software with gcc-7.2 , I got this problem

**g++ ./src/seq.o ./src/tandem_chain.o ./src/partition.o ./src/tide_hunter.o ./src/abpoa_align.o ./src/ksw2_align.o ./src/main.o ./src/tandem_hit.o ./src/gen_cons.o ./src/edlib_align.o ./src/utils.o ./ksw2/ksw2_extz2_sse.o ./ksw2/ksw2_gg2_sse.o ./edlib/src/edlib.o -L./abPOA/lib -labpoa -lm -lz -lpthread -o bin/TideHunter
/home/lzl/miniconda3/envs/gcc-7/bin/../lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../libstdc++.so: undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'**

How to solve it? I also got some problems when I compliled it with gcc-4.8 and gcc-4.9 but sovled in gcc-7.2. Considering potential bugs, I think a binary package is more friendly.

**Comment by yangao07** [comment]
Sorry about the compiling problem.
Please try the pre-built binary file attached and let me know if it works on your machine.

Yan

[TideHunter-v1.1_x64-linux.tar.gz](https://github.com/yangao07/TideHunter/files/3732270/TideHunter-v1.1_x64-linux.tar.gz)

**Comment by colinliuzelin** [comment]
> Sorry about the compiling problem.
> Please try the pre-built binary file attached and let me know if it works on your machine.
> 
> Yan
> 
> [TideHunter-v1.1_x64-linux.tar.gz](https://github.com/yangao07/TideHunter/files/3732270/TideHunter-v1.1_x64-linux.tar.gz)

Thank you! The binary file worked well on my computer.
