### ISSUE TITLE
-s (--single-copy) 

### ISSUE THREAD

**Issue by bvergnes** [yangao07/TideHunter#14]
Hi Yan,
thanks again for updating this very useful software.
i wanted to try the new optional output (single-copy full-length sequence when 5/3 adapters are provided). In v1.5.4 version, i get the single-copy output when adding the -F option. Here (v1.5.5), -F option only output sequences with copy number >=2 and when i add -s option, i have this error message : invalid option -- 's'

TideHunter -t 12 -f 2 -F -s -k 6 -a 1 -5 forward.fa -3 reverse.fa input.fastq > cons.out
invalid option -- 's'

Something wrong with my command line?

**Comment by yangao07** [comment]
Sorry, I just realized that the update was not correct. Let me fix it quickly.

**Comment by yangao07** [comment]
Hi, the -s option should be fixed now.
