### ISSUE TITLE
Illegal instruction: 4 issue on MacOS 12.01

### ISSUE THREAD

**Issue by santiago-es** [yangao07/TideHunter#5]
Hi,

I installed TideHunter with bioconda and attempted the test data command 

TideHunter TideHunter/test_data/test_1000x10.fa > cons.fa

which fails with 

"Illegal instruction 4". 

My understanding is this is an issue due to an incompatibility between the source code of TideHunter and the current MacOS version. Is there a workaround to this? Thanks!

**Comment by yangao07** [comment]
Is your MAC arm-based?
That may be the reason.

**Comment by santiago-es** [comment]
Hi,

Yes, my Mac has the M1 silicon chip currently.

I also tried compiling directly from source instead of conda and run into issues compiling because of similar issues with the architecture. Is there a fix?

**Comment by yangao07** [comment]
The abpoa used in TideHunter is not the latest, and the latest should fix this.

You can try to replace the abpoa sub-folder with https://github.com/yangao07/abPOA, remember use `git clone --recursive`.

I will update the TideHunter repo later.

Yan

**Comment by santiago-es** [comment]
The makefile in the Abpoa folder now runs to completion but the makefile in the TideHunter main directory fails with error message “invalid input constraint ‘a’ in asm” and also "error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size"

These seem to be problems with clang. I’m running clang 13.00 and have LLVM installed from brew, latest version.

Santiago E. Sanchez

Stanford Medical School | MD/PhD Student, Artandi Lab
Cambridge University '18 | M.Phil Chemistry
(832) 768 6242
he/him

**Comment by yangao07** [comment]
Have you tried gcc?
ARM+clang seems to not work right now.

**Comment by santiago-es** [comment]
I uncommented the CC= Gcc flag from the makefiles but for some reason clang is still being called. Is the makefile in the main directory and the one in AbPOA the only ones?

Santiago

**Comment by yangao07** [comment]
You can try `make CC=gcc`.

**Comment by santiago-es** [comment]
Hi Yan,

I tried that but runs into the same error.

I think the issue is with the header in simd_instruction.h

For some reason, the header is calling files for x86 Intel architecture, which is not compatible with the M1 silicon architecture. I tried deleting the x86 references but then an error is called from abpoa.h during make because the SIMDi type becomes undefined.

Any ideas?

Santiago E. Sanchez

Stanford Medical School | MD/PhD Student, Artandi Lab
Cambridge University '18 | M.Phil Chemistry
(832) 768 6242
he/him

**Comment by santiago-es** [comment]
I've made some progress now. 

After cloning in the most up-to-date AbPOA, I was able to successfully compile the abPOA subfolder by changing -march=native to -mcpu=apple-m1 

Also, in the simd_instruction.h files in both the src and include folders, the include flag should be
#include <arm_neon.h>

After that ABPOA compiles and functions as expected.

TideHunter still will not compile after running "make CC=gcc" 
With this error: 

Undefined symbols for architecture arm64:
  "_ksw_extz2_sse", referenced from:
      _ksw2_global in ksw2_align.o
      _ksw2_global_with_cigar in ksw2_align.o
      _ksw2_right_ext in ksw2_align.o
      _ksw2_left_ext in ksw2_align.o
      _ksw2_right_extend in ksw2_align.o
      _ksw2_left_extend in ksw2_align.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/TideHunter] Error 1

But here I'm at a loss for where to go.

**Comment by yangao07** [comment]
Hi, just updated the Makefile in TideHunter:

`
ifneq ($(armv7),) # for ARMv7
        KSW2_SIMD_FLAG   =  -march=armv7-a -mfpu=neon -D__AVX2_
else
ifneq ($(armv8),) # for ARMv8
ifneq ($(aarch64),) # for Aarch64
        KSW2_SIMD_FLAG   =  -march=armv8-a+simd -D__AVX2__
else # for Aarch32
        KSW2_SIMD_FLAG   =  -march=armv8-a+simd -mfpu=auto -D__
endif
endif
endif
`
Please choose the flag for your machine, e.g. `make clean_all all armv8=1 aarch64=1`.

**Comment by santiago-es** [comment]
Working now! thanks so much for your help.
