### ISSUE TITLE
Illegal instruction (core dumped) from "TideHunter ./test_data/test_1000x10.fa > cons.fa"

### ISSUE THREAD

**Issue by Yuchiho** [yangao07/TideHunter#7]
Hello Yan,

After TideHunter-v1.5.3 was installed, I tried the test data with "TideHunter ./test_data/test_50x4.fa > cons.fa".
Then it shows the error: "Illegal instruction (core dumped)"
I'm using Ubuntu20.04 as windows subsystem by the way.
Would you help me to fix this problem? 
Thank you.

Best regards,
Yuchi Ho

**Comment by yangao07** [comment]
How did you install TideHunter, from source code or conda?

**Comment by Yuchiho** [comment]
I tried both way separately, but it showed the same error.
"wget https://github.com/yangao07/TideHunter/releases/download/v1.5.3/TideHunter-v1.5.3.tar.gz
tar -zxvf TideHunter-v1.5.3.tar.gz && cd TideHunter-v1.5.3"
"conda install -c bioconda tidehunter"

**Comment by yangao07** [comment]
Can you type `cat /proc/cpuinfo  | grep -E "sse|avx"` and paste the ouput here?

**Comment by Yuchiho** [comment]
cat /proc/cpuinfo | grep -E "sse|avx"
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx fxsr_opt rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni ssse3 cx16 sse4_1 sse4_2 hypervisor lahf_lm cr8_legacy 3dnowprefetch ssbd vmmcall fsgsbase arat

**Comment by yangao07** [comment]
Seems like your CPU is an old model. 
To re-compile, you can try `make clean_all; make sse41=1` in the TideHunter download folder.

Let me know if this works.

**Comment by Yuchiho** [comment]
Thank you for your reply.

Below is my input code in the TideHunter download folder, and it shows another error.
 
My Input :  
" ~/TideHunter-v1.5.3$ make clean_all; make sse41=1 " 

Error:
"
rm -f ./src/*.o ./bin/TideHunter
rm -f ./lib/libabpoa.a; \
cd ./abPOA; make clean; \
make[1]: 進入目錄「/home/gordonho/TideHunter-v1.5.3/abPOA」
rm -f ./src/*.[oa] ./lib/*.[oa] ./bin/abpoa
make[1]: 離開目錄「/home/gordonho/TideHunter-v1.5.3/abPOA」
rm -f ./ksw2/*.o
rm -f ./edlib/src/edlib.o
cc -c -Wall -O3 -Wno-unused-variable -Wno-unused-function -Wno-misleading-indentation   -I./abPOA/include src/abpoa_cons.c -o src/abpoa_cons.o
make: cc: Command not found
make: *** [Makefile:105：src/abpoa_cons.o] 錯誤 127
"

**Comment by yangao07** [comment]
I see. 
I think this machine is not able to run the program, cause of the lack of some basic commands.
You need to run it on other machines.

**Comment by Yuchiho** [comment]
I just installed gcc. and the error being like:
"
rm -f ./src/*.o ./bin/TideHunter
rm -f ./lib/libabpoa.a; \
cd ./abPOA; make clean; \

make[1]: 進入目錄「/home/gordonho/TideHunter-v1.5.3/abPOA」
rm -f ./src/*.[oa] ./lib/*.[oa] ./bin/abpoa
make[1]: 離開目錄「/home/gordonho/TideHunter-v1.5.3/abPOA」
rm -f ./ksw2/*.o
rm -f ./edlib/src/edlib.o
cc -c -Wall -O3 -Wno-unused-variable -Wno-unused-function -Wno-misleading-indentation   -I./abPOA/include src/abpoa_cons.c -o src/abpoa_cons.o
In file included from src/abpoa_cons.c:5:
src/tidehunter.h:3:10: fatal error: zlib.h: 沒有此一檔案或目錄
    3 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:105：src/abpoa_cons.o] 錯誤 1
"

**Comment by yangao07** [comment]
Hi, apparently, zlib is needed to be installed.

**Comment by Yuchiho** [comment]
Hello Yan,
It works as I changed another machine. 
Thank you for your reply.
